defaults:
  - data: data
  - extract: extract

hydra:
  output_subdir: null
  # Hydra single-run working directory.
  run:
    dir: .
  # Hydra multi-run working directories.
  sweep:
    dir: .
    subdir: .
